// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Onnx
{
    [global::ProtoBuf.ProtoContract()]
    public partial class AttributeProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(21, Name = @"ref_attr_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RefAttrName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(13, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString { get; set; } = "";

        [global::ProtoBuf.ProtoMember(20, Name = @"type")]
        public AttributeType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"f")]
        public float F { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"i")]
        public long I { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"s")]
        public byte[] S { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"t")]
        public TensorProto T { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"g")]
        public GraphProto G { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"sparse_tensor")]
        public SparseTensorProto SparseTensor { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"floats", IsPacked = true)]
        public float[] Floats { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"ints", IsPacked = true)]
        public long[] Ints { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"strings")]
        public global::System.Collections.Generic.List<byte[]> Strings { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(10, Name = @"tensors")]
        public global::System.Collections.Generic.List<TensorProto> Tensors { get; } = new global::System.Collections.Generic.List<TensorProto>();

        [global::ProtoBuf.ProtoMember(11, Name = @"graphs")]
        public global::System.Collections.Generic.List<GraphProto> Graphs { get; } = new global::System.Collections.Generic.List<GraphProto>();

        [global::ProtoBuf.ProtoMember(23, Name = @"sparse_tensors")]
        public global::System.Collections.Generic.List<SparseTensorProto> SparseTensors { get; } = new global::System.Collections.Generic.List<SparseTensorProto>();

        [global::ProtoBuf.ProtoContract()]
        public enum AttributeType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNDEFINED")]
            Undefined = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"FLOAT")]
            Float = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"INT")]
            Int = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"STRING")]
            String = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"TENSOR")]
            Tensor = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"GRAPH")]
            Graph = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"SPARSE_TENSOR")]
            SparseTensor = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"FLOATS")]
            Floats = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"INTS")]
            Ints = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"STRINGS")]
            Strings = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"TENSORS")]
            Tensors = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"GRAPHS")]
            Graphs = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"SPARSE_TENSORS")]
            SparseTensors = 12,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ValueInfoProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public TypeProto Type { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NodeProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"input")]
        public global::System.Collections.Generic.List<string> Inputs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2, Name = @"output")]
        public global::System.Collections.Generic.List<string> Outputs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"op_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OpType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"domain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Domain { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"attribute")]
        public global::System.Collections.Generic.List<AttributeProto> Attributes { get; } = new global::System.Collections.Generic.List<AttributeProto>();

        [global::ProtoBuf.ProtoMember(6, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrainingInfoProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"initialization")]
        public GraphProto Initialization { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"algorithm")]
        public GraphProto Algorithm { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"initialization_binding")]
        public global::System.Collections.Generic.List<StringStringEntryProto> InitializationBindings { get; } = new global::System.Collections.Generic.List<StringStringEntryProto>();

        [global::ProtoBuf.ProtoMember(4, Name = @"update_binding")]
        public global::System.Collections.Generic.List<StringStringEntryProto> UpdateBindings { get; } = new global::System.Collections.Generic.List<StringStringEntryProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ModelProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ir_version")]
        public long IrVersion { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"opset_import")]
        public global::System.Collections.Generic.List<OperatorSetIdProto> OpsetImports { get; } = new global::System.Collections.Generic.List<OperatorSetIdProto>();

        [global::ProtoBuf.ProtoMember(2, Name = @"producer_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ProducerName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"producer_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ProducerVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"domain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Domain { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"model_version")]
        public long ModelVersion { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"graph")]
        public GraphProto Graph { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"metadata_props")]
        public global::System.Collections.Generic.List<StringStringEntryProto> MetadataProps { get; } = new global::System.Collections.Generic.List<StringStringEntryProto>();

        [global::ProtoBuf.ProtoMember(20, Name = @"training_info")]
        public global::System.Collections.Generic.List<TrainingInfoProto> TrainingInfoes { get; } = new global::System.Collections.Generic.List<TrainingInfoProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StringStringEntryProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Value { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TensorAnnotation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tensor_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TensorName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"quant_parameter_tensor_names")]
        public global::System.Collections.Generic.List<StringStringEntryProto> QuantParameterTensorNames { get; } = new global::System.Collections.Generic.List<StringStringEntryProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GraphProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"node")]
        public global::System.Collections.Generic.List<NodeProto> Nodes { get; } = new global::System.Collections.Generic.List<NodeProto>();

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"initializer")]
        public global::System.Collections.Generic.List<TensorProto> Initializers { get; } = new global::System.Collections.Generic.List<TensorProto>();

        [global::ProtoBuf.ProtoMember(15, Name = @"sparse_initializer")]
        public global::System.Collections.Generic.List<SparseTensorProto> SparseInitializers { get; } = new global::System.Collections.Generic.List<SparseTensorProto>();

        [global::ProtoBuf.ProtoMember(10, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"input")]
        public global::System.Collections.Generic.List<ValueInfoProto> Inputs { get; } = new global::System.Collections.Generic.List<ValueInfoProto>();

        [global::ProtoBuf.ProtoMember(12, Name = @"output")]
        public global::System.Collections.Generic.List<ValueInfoProto> Outputs { get; } = new global::System.Collections.Generic.List<ValueInfoProto>();

        [global::ProtoBuf.ProtoMember(13, Name = @"value_info")]
        public global::System.Collections.Generic.List<ValueInfoProto> ValueInfoes { get; } = new global::System.Collections.Generic.List<ValueInfoProto>();

        [global::ProtoBuf.ProtoMember(14, Name = @"quantization_annotation")]
        public global::System.Collections.Generic.List<TensorAnnotation> QuantizationAnnotations { get; } = new global::System.Collections.Generic.List<TensorAnnotation>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TensorProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dims", IsPacked = true)]
        public long[] Dims { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int data_type { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Segment segment { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"float_data", IsPacked = true)]
        public float[] FloatDatas { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"int32_data", IsPacked = true)]
        public int[] Int32Datas { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"string_data")]
        public global::System.Collections.Generic.List<byte[]> StringDatas { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(7, Name = @"int64_data", IsPacked = true)]
        public long[] Int64Datas { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"raw_data")]
        public byte[] RawData { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"external_data")]
        public global::System.Collections.Generic.List<StringStringEntryProto> ExternalDatas { get; } = new global::System.Collections.Generic.List<StringStringEntryProto>();

        [global::ProtoBuf.ProtoMember(14)]
        public DataLocation data_location { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"double_data", IsPacked = true)]
        public double[] DoubleDatas { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"uint64_data", IsPacked = true)]
        public ulong[] Uint64Datas { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Segment : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"begin")]
            public long Begin { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"end")]
            public long End { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum DataType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNDEFINED")]
            Undefined = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"FLOAT")]
            Float = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"UINT8")]
            Uint8 = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"INT8")]
            Int8 = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"UINT16")]
            Uint16 = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"INT16")]
            Int16 = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"INT32")]
            Int32 = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"INT64")]
            Int64 = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"STRING")]
            String = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"BOOL")]
            Bool = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"FLOAT16")]
            Float16 = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"DOUBLE")]
            Double = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"UINT32")]
            Uint32 = 12,
            [global::ProtoBuf.ProtoEnum(Name = @"UINT64")]
            Uint64 = 13,
            [global::ProtoBuf.ProtoEnum(Name = @"COMPLEX64")]
            Complex64 = 14,
            [global::ProtoBuf.ProtoEnum(Name = @"COMPLEX128")]
            Complex128 = 15,
            [global::ProtoBuf.ProtoEnum(Name = @"BFLOAT16")]
            Bfloat16 = 16,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum DataLocation
        {
            [global::ProtoBuf.ProtoEnum(Name = @"DEFAULT")]
            Default = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"EXTERNAL")]
            External = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SparseTensorProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"values")]
        public TensorProto Values { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"indices")]
        public TensorProto Indices { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"dims", IsPacked = true)]
        public long[] Dims { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TensorShapeProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dim")]
        public global::System.Collections.Generic.List<Dimension> Dims { get; } = new global::System.Collections.Generic.List<Dimension>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Dimension : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"dim_value")]
            public long DimValue
            {
                get { return __pbn__value.Is(1) ? __pbn__value.Int64 : default; }
                set { __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(1, value); }
            }
            public bool ShouldSerializeDimValue() => __pbn__value.Is(1);
            public void ResetDimValue() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 1);

            private global::ProtoBuf.DiscriminatedUnion64Object __pbn__value;

            [global::ProtoBuf.ProtoMember(2, Name = @"dim_param")]
            [global::System.ComponentModel.DefaultValue("")]
            public string DimParam
            {
                get { return __pbn__value.Is(2) ? ((string)__pbn__value.Object) : ""; }
                set { __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(2, value); }
            }
            public bool ShouldSerializeDimParam() => __pbn__value.Is(2);
            public void ResetDimParam() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 2);

            [global::ProtoBuf.ProtoMember(3, Name = @"denotation")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Denotation { get; set; } = "";

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TypeProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tensor_type")]
        public Tensor TensorType
        {
            get { return __pbn__value.Is(1) ? ((Tensor)__pbn__value.Object) : default; }
            set { __pbn__value = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
        }
        public bool ShouldSerializeTensorType() => __pbn__value.Is(1);
        public void ResetTensorType() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__value, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__value;

        [global::ProtoBuf.ProtoMember(4, Name = @"sequence_type")]
        public Sequence SequenceType
        {
            get { return __pbn__value.Is(4) ? ((Sequence)__pbn__value.Object) : default; }
            set { __pbn__value = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeSequenceType() => __pbn__value.Is(4);
        public void ResetSequenceType() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__value, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"map_type")]
        public Map MapType
        {
            get { return __pbn__value.Is(5) ? ((Map)__pbn__value.Object) : default; }
            set { __pbn__value = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializeMapType() => __pbn__value.Is(5);
        public void ResetMapType() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__value, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"denotation")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Denotation { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public partial class Tensor : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"elem_type")]
            public int ElemType { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"shape")]
            public TensorShapeProto Shape { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Sequence : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"elem_type")]
            public TypeProto ElemType { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Map : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"key_type")]
            public int KeyType { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"value_type")]
            public TypeProto ValueType { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OperatorSetIdProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"domain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Domain { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"version")]
        public long Version { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Version
    {
        [global::ProtoBuf.ProtoEnum(Name = @"_START_VERSION")]
        StartVersion = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION_2017_10_10")]
        IrVersion20171010 = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION_2017_10_30")]
        IrVersion20171030 = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION_2017_11_3")]
        IrVersion2017113 = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION_2019_1_22")]
        IrVersion2019122 = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION_2019_3_18")]
        IrVersion2019318 = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION_2019_9_19")]
        IrVersion2019919 = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION")]
        IrVersion = 7,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
